name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"

  ENV:
    BINARY_NAME: start_working
    FUNCTION_NAME: work_statement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Zip
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --release
      - run: |
          sudo mv ./target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }} ./bootstrap
          sudo chmod 755 ./bootstrap
          zip lambda.zip ./bootstrap
      - name: Push to aws/lambda
        uses: stcalica/update-lambda@master
        with:
          package: lambda.zip
          function-name: ${{ env.FUNCTION_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
