name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Zip
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --release
      - run: |
          sudo mv ./target/x86_64-unknown-linux-musl/release/start_working ./bootstrap
          sudo chmod 755 ./bootstrap
          zip lambda.zip ./bootstrap
      - name: Push to aws/lambda
        uses: stcalica/update-lambda@master
        with:
          package: lambda.zip
          function-name: work_statement
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
